version: '3.6'

services:
  postgres:
    container_name: tiktok_analyzer_postgres
    image: postgres:14.4
    restart: always
    ports: 
      - 0.0.0.0:15432:5432
    volumes:
      - ./db_data/pgdb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Abc12345
      - POSTGRES_DB=postgres