"""fix data type

Revision ID: 017ab9d281ae
Revises: f3aab61bf72c
Create Date: 2023-05-29 18:25:46.883628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017ab9d281ae'
down_revision = 'f3aab61bf72c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
