"""fix data type

Revision ID: 1a27c1522829
Revises: afef19f1a4b5
Create Date: 2023-05-29 18:17:29.598807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a27c1522829'
down_revision = 'afef19f1a4b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
