"""fix data type

Revision ID: afef19f1a4b5
Revises: 27ccbcd90084
Create Date: 2023-05-29 18:13:52.026852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afef19f1a4b5'
down_revision = '27ccbcd90084'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'author', ['tiktok_id'])
    op.add_column('music', sa.Column('total_digg_count', sa.Integer(), nullable=True))
    op.add_column('music', sa.Column('total_share_count', sa.Integer(), nullable=True))
    op.add_column('music', sa.Column('total_play_count', sa.Integer(), nullable=True))
    op.add_column('music', sa.Column('total_comment_count', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'tiktok_music', ['tiktok_music_id'])
    op.drop_column('tiktok_music', 'tiktok_name')
    op.drop_column('tiktok_music', 'author_name')
    op.create_unique_constraint(None, 'tiktok_post', ['tiktok_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tiktok_post', type_='unique')
    op.add_column('tiktok_music', sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tiktok_music', sa.Column('tiktok_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tiktok_music', type_='unique')
    op.drop_column('music', 'total_comment_count')
    op.drop_column('music', 'total_play_count')
    op.drop_column('music', 'total_share_count')
    op.drop_column('music', 'total_digg_count')
    op.drop_constraint(None, 'author', type_='unique')
    # ### end Alembic commands ###
