"""fix data type

Revision ID: f3aab61bf72c
Revises: 1a27c1522829
Create Date: 2023-05-29 18:19:09.036904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3aab61bf72c'
down_revision = '1a27c1522829'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiktok_music', sa.Column('tiktok_id', sa.String(), nullable=False))
    op.drop_constraint('tiktok_music_tiktok_music_id_key', 'tiktok_music', type_='unique')
    op.create_unique_constraint(None, 'tiktok_music', ['tiktok_id'])
    op.drop_column('tiktok_music', 'tiktok_music_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiktok_music', sa.Column('tiktok_music_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tiktok_music', type_='unique')
    op.create_unique_constraint('tiktok_music_tiktok_music_id_key', 'tiktok_music', ['tiktok_music_id'])
    op.drop_column('tiktok_music', 'tiktok_id')
    # ### end Alembic commands ###
